config/routes.rb
MAPSbeta::Application.routes.draw do
  resources :process_steps

  resources :process_flows

  get "flow_generator/index"

  resources :parameters

  resources :fab_processes

  root :to => 'flow_generator#index', :as => 'flow_generator'

end

app/controllers/fab_processes_controller.rb
class FabProcessesController < ApplicationController
  # GET /fab_processes
  # GET /fab_processes.xml
  def index
    @fab_processes = FabProcess.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @fab_processes }
    end
  end

  # GET /fab_processes/1
  # GET /fab_processes/1.xml
  def show
    @fab_process = FabProcess.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @fab_process }
    end
  end

  # GET /fab_processes/new
  # GET /fab_processes/new.xml
  def new
    @fab_process = FabProcess.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @fab_process }
    end
  end

  # GET /fab_processes/1/edit
  def edit
    @fab_process = FabProcess.find(params[:id])
  end

  # POST /fab_processes
  # POST /fab_processes.xml
  def create
    @fab_process = FabProcess.new(params[:fab_process])

    respond_to do |format|
      if @fab_process.save
        format.html { redirect_to(@fab_process, :notice => 'Fab process was successfully created.') }
        format.xml  { render :xml => @fab_process, :status => :created, :location => @fab_process }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @fab_process.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /fab_processes/1
  # PUT /fab_processes/1.xml
  def update
    @fab_process = FabProcess.find(params[:id])

    respond_to do |format|
      if @fab_process.update_attributes(params[:fab_process])
        format.html { redirect_to(@fab_process, :notice => 'Fab process was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @fab_process.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /fab_processes/1
  # DELETE /fab_processes/1.xml
  def destroy
    @fab_process = FabProcess.find(params[:id])
    @fab_process.destroy

    respond_to do |format|
      format.html { redirect_to(fab_processes_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/fab_processes_helper.rb
module FabProcessesHelper
end

app/views/fab_processes/_form.html.erb
<%= form_for(@fab_process) do |f| %>
  <% if @fab_process.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fab_process.errors.count, "error") %> prohibited this fab_process from being saved:</h2>

      <ul>
      <% @fab_process.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :rows => 6 %>
  </div>
   <div class="field">
    <%= f.label :parameter_id %><br />
    <%= f.text_field :parameter_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fab_processes/edit.html.erb
<h1>Editing fab_process</h1>

<%= render 'form' %>

<%= link_to 'Show', @fab_process %> |
<%= link_to 'Back', fab_processes_path %>

app/views/fab_processes/index.html.erb
<div id="fab_process_list">
  <h1>Listing of Fabrication Processes</h1>

  <table>
  <% @fab_processes.each do |fab_process| %>
    <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">

      <td class="list_description">
        <dl>
          <dt><%= fab_process.name %></dt>
          <dd><%= truncate(strip_tags(fab_process.description), :length => 200)%></dd>
          <dt><i><%= fab_process.category %></i></dt>
          <dt><%= fab_process.parameter_id%></dt>
        </dl>
      </td>

      <td class="list_actions">

        <%= link_to 'Show', fab_process %><br/>
        <%= link_to 'Edit', edit_fab_process_path(fab_process) %><br/>
        <%= link_to 'Destroy', fab_process, 
                    :confirm => 'Are you sure?',
                    :method => :delete %>
      </td>
    </tr>
  <% end %>
  </table>
</div>

<br />

<%= link_to 'New Fabrication Process', new_fab_process_path %>

app/views/fab_processes/new.html.erb
<h1>New Fabrication Process</h1>

<%= render 'form' %>

<%= link_to 'Back', fab_processes_path %>

app/views/fab_processes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @fab_process.name %>
</p>

<p>
  <b>Category:</b>
  <%= @fab_process.category %>
</p>

<p>
  <b>Parameter:</b>
  <%= @fab_process.parameter_id %>
</p>


<%= link_to 'Edit', edit_fab_process_path(@fab_process) %> |
<%= link_to 'Back', fab_processes_path %>