config/routes.rb
MAPSbeta::Application.routes.draw do
  resources :process_steps

  resources :process_flows

  get "flow_generator/index"

  resources :parameters

  resources :fab_processes

  root :to => 'flow_generator#index', :as => 'flow_generator'

end

app/models/process_step.rb
class ProcessStep < ActiveRecord::Base
	belongs_to :fab_process
	belongs_to :process_flow
end

app/controllers/process_steps_controller.rb
class ProcessStepsController < ApplicationController
  # GET /process_steps
  # GET /process_steps.xml
  def index
    @process_steps = ProcessStep.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @process_steps }
    end
  end

  # GET /process_steps/1
  # GET /process_steps/1.xml
  def show
    @process_step = ProcessStep.find(params[:id])
	@process_steps_count = ProcessStep.count
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @process_step }
    end
  end

  # GET /process_steps/new
  # GET /process_steps/new.xml
  def new
    @process_step = ProcessStep.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @process_step }
    end
  end

  # GET /process_steps/1/edit
  def edit
    @process_step = ProcessStep.find(params[:id])
  end

  # POST /process_steps
  # POST /process_steps.xml
  def create
  	@process_flow = current_process_flow
  	fab_process = FabProcess.find(params[:fab_process_id])
  	@process_step = @process_flow.process_steps.build(:fab_process => fab_process)
  
    respond_to do |format|
      if @process_step.save
        format.html { redirect_to(@process_step.process_flow) }
        format.xml  { render :xml => @process_step, :status => :created, :location => @process_step }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @process_step.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /process_steps/1
  # PUT /process_steps/1.xml
  def update
    @process_step = ProcessStep.find(params[:id])

    respond_to do |format|
      if @process_step.update_attributes(params[:process_step])
        format.html { redirect_to(@process_step, :notice => 'Process step was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @process_step.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /process_steps/1
  # DELETE /process_steps/1.xml
  def destroy
    @process_step = ProcessStep.find(params[:id])
    @process_step.destroy

    respond_to do |format|
      format.html { redirect_to(process_steps_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/process_steps_helper.rb
module ProcessStepsHelper
end

app/views/process_steps/_form.html.erb
<%= form_for(@process_step) do |f| %>
  <% if @process_step.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@process_step.errors.count, "error") %> prohibited this process_step from being saved:</h2>

      <ul>
      <% @process_step.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fab_process_id %><br />
    <%= f.text_field :fab_process_id %>
  </div>
  <div class="field">
    <%= f.label :process_flow_id %><br />
    <%= f.text_field :process_flow_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/process_steps/edit.html.erb
<h1>Editing process_step</h1>

<%= render 'form' %>

<%= link_to 'Show', @process_step %> |
<%= link_to 'Back', process_steps_path %>

app/views/process_steps/index.html.erb
<h1>Listing process_steps</h1>

<table>
  <tr>
    <th>Fab process</th>
    <th>Process flow</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @process_steps.each do |process_step| %>
  <tr>
    <td><%= process_step.fab_process_id %></td>
    <td><%= process_step.process_flow_id %></td>
    <td><%= link_to 'Show', process_step %></td>
    <td><%= link_to 'Edit', edit_process_step_path(process_step) %></td>
    <td><%= link_to 'Destroy', process_step, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Process step', new_process_step_path %>

app/views/process_steps/new.html.erb
<h1>New process_step</h1>

<%= render 'form' %>

<%= link_to 'Back', process_steps_path %>

app/views/process_steps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Fab process:</b>
  <%= @process_step.fab_process_id %>
</p>

<p>
  <b>Process flow:</b>
  <%= @process_step.process_flow_id %>
</p>


<%= link_to 'Edit', edit_process_step_path(@process_step) %> |
<%= link_to 'Back', process_steps_path %>