config/routes.rb
MAPSbeta::Application.routes.draw do
  resources :process_steps

  resources :process_flows

  get "flow_generator/index"

  resources :parameters

  resources :fab_processes

  root :to => 'flow_generator#index', :as => 'flow_generator'

end

app/models/process_flow.rb
class ProcessFlow < ActiveRecord::Base
	has_many :process_steps, :dependent => :destroy
end

app/controllers/process_flows_controller.rb
class ProcessFlowsController < ApplicationController
  # GET /process_flows
  # GET /process_flows.xml
  def index
    @process_flows = ProcessFlow.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @process_flows }
    end
  end

  # GET /process_flows/1
  # GET /process_flows/1.xml
  def show
  	begin
    @process_flow = ProcessFlow.find(params[:id])
    
    #Error handling for bad process_flow_id
   	rescue ActiveRecord::RecordNotFound
   		logger.error "Attempt to access invalid process_flow #{params[:id]}"
   		redirect_to flow_generator_url, :notice => 'Invalid process_flow'
   	else
   		respond_to do |format|
	    	format.html # show.html.erb
	    	format.xml  { render :xml => @process_flow }
    	end
  	end
  end
  # GET /process_flows/new
  # GET /process_flows/new.xml
  def new
    @process_flow = ProcessFlow.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @process_flow }
    end
  end

  # GET /process_flows/1/edit
  def edit
    @process_flow = ProcessFlow.find(params[:id])
  end

  # POST /process_flows
  # POST /process_flows.xml
  def create
    @process_flow = ProcessFlow.new(params[:process_flow])

    respond_to do |format|
      if @process_flow.save
        format.html { redirect_to(@process_flow, :notice => 'Process flow was successfully created.') }
        format.xml  { render :xml => @process_flow, :status => :created, :location => @process_flow }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @process_flow.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /process_flows/1
  # PUT /process_flows/1.xml
  def update
    @process_flow = ProcessFlow.find(params[:id])

    respond_to do |format|
      if @process_flow.update_attributes(params[:process_flow])
        format.html { redirect_to(@process_flow, :notice => 'Process flow was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @process_flow.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /process_flows/1
  # DELETE /process_flows/1.xml
  def destroy
    @process_flow = ProcessFlow.find(params[:id])
    @process_flow.destroy
    session[:process_flow_id] = nil
    
    respond_to do |format|
      format.html { redirect_to(flow_generator_url, :notice => 'Process flow deleted') }
      format.xml  { head :ok }
    end
  end
end

app/helpers/process_flows_helper.rb
module ProcessFlowsHelper
end

app/views/process_flows/_form.html.erb
<%= form_for(@process_flow) do |f| %>
  <% if @process_flow.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@process_flow.errors.count, "error") %> prohibited this process_flow from being saved:</h2>

      <ul>
      <% @process_flow.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/process_flows/edit.html.erb
<h1>Editing process_flow</h1>

<%= render 'form' %>

<%= link_to 'Show', @process_flow %> |
<%= link_to 'Back', process_flows_path %>

app/views/process_flows/index.html.erb
<h1>Listing process_flows</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @process_flows.each do |process_flow| %>
  <tr>
    <td><%= link_to 'Show', process_flow %></td>
    <td><%= link_to 'Edit', edit_process_flow_path(process_flow) %></td>
    <td><%= link_to 'Destroy', process_flow, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Process flow', new_process_flow_path %>

app/views/process_flows/new.html.erb
<h1>New process_flow</h1>

<%= render 'form' %>

<%= link_to 'Back', process_flows_path %>

app/views/process_flows/show.html.erb
<div class="process_flow_title">Your Process Flow</div>
<table>
	
  <% @process_flow.process_steps.each do |pstep| %>
    <tr>
      <td><%= pstep.fab_process.name %></td>
      <td><%= pstep.fab_process.category %></td>
    </tr>
  <% end %>
  
</table>

<%= @process_steps_count %></td>

<%= button_to 'Reset Process Flow', @process_flow, :method => :delete,
	:confirm => 'Are you sure?' %>