config/routes.rb
MAPSbeta::Application.routes.draw do
  resources :process_steps

  resources :process_flows

  get "flow_generator/index"

  resources :parameters

  resources :fab_processes

  root :to => 'flow_generator#index', :as => 'flow_generator'

end

app/models/parameter.rb
class Parameter < ActiveRecord::Base
end

app/controllers/parameters_controller.rb
class ParametersController < ApplicationController
  # GET /parameters
  # GET /parameters.xml
  def index
    @parameters = Parameter.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @parameters }
    end
  end

  # GET /parameters/1
  # GET /parameters/1.xml
  def show
    @parameter = Parameter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @parameter }
    end
  end

  # GET /parameters/new
  # GET /parameters/new.xml
  def new
    @parameter = Parameter.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @parameter }
    end
  end

  # GET /parameters/1/edit
  def edit
    @parameter = Parameter.find(params[:id])
  end

  # POST /parameters
  # POST /parameters.xml
  def create
    @parameter = Parameter.new(params[:parameter])

    respond_to do |format|
      if @parameter.save
        format.html { redirect_to(@parameter, :notice => 'Parameter was successfully created.') }
        format.xml  { render :xml => @parameter, :status => :created, :location => @parameter }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @parameter.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /parameters/1
  # PUT /parameters/1.xml
  def update
    @parameter = Parameter.find(params[:id])

    respond_to do |format|
      if @parameter.update_attributes(params[:parameter])
        format.html { redirect_to(@parameter, :notice => 'Parameter was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @parameter.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /parameters/1
  # DELETE /parameters/1.xml
  def destroy
    @parameter = Parameter.find(params[:id])
    @parameter.destroy

    respond_to do |format|
      format.html { redirect_to(parameters_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/parameters_helper.rb
module ParametersHelper
end

app/views/parameters/_form.html.erb
<%= form_for(@parameter) do |f| %>
  <% if @parameter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@parameter.errors.count, "error") %> prohibited this parameter from being saved:</h2>

      <ul>
      <% @parameter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :optimum_value %><br />
    <%= f.text_field :optimum_value %>
  </div>
  <div class="field">
    <%= f.label :tolerance %><br />
    <%= f.text_field :tolerance %>
  </div>
  <div class="field">
    <%= f.label :units %><br />
    <%= f.text_field :units %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/parameters/edit.html.erb
<h1>Editing parameter</h1>

<%= render 'form' %>

<%= link_to 'Show', @parameter %> |
<%= link_to 'Back', parameters_path %>

app/views/parameters/index.html.erb
<h1>Listing parameters</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Optimum value</th>
    <th>Tolerance</th>
    <th>Units</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @parameters.each do |parameter| %>
  <tr>
    <td><%= parameter.name %></td>
    <td><%= parameter.optimum_value %></td>
    <td><%= parameter.tolerance %></td>
    <td><%= parameter.units %></td>
    <td><%= link_to 'Show', parameter %></td>
    <td><%= link_to 'Edit', edit_parameter_path(parameter) %></td>
    <td><%= link_to 'Destroy', parameter, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Parameter', new_parameter_path %>

app/views/parameters/new.html.erb
<h1>New parameter</h1>

<%= render 'form' %>

<%= link_to 'Back', parameters_path %>

app/views/parameters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @parameter.name %>
</p>

<p>
  <b>Optimum value:</b>
  <%= @parameter.optimum_value %>
</p>

<p>
  <b>Tolerance:</b>
  <%= @parameter.tolerance %>
</p>

<p>
  <b>Units:</b>
  <%= @parameter.units %>
</p>


<%= link_to 'Edit', edit_parameter_path(@parameter) %> |
<%= link_to 'Back', parameters_path %>